name: Claude Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created, edited]
  issue_comment:
    types: [created, edited]
    
jobs:
  process-pull-request:
    name: Process Pull Request
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
      
      - name: Run Claude Code Reviewer
        uses: Felipemantilla01/claude-code-reviewer@main
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
